### ISSUE TITLE
Fix the name of music tracks

### ISSUE THREAD

**Issue by kemenaran** [zladx/LADX-Disassembly#221]
There's a list that [matches music tracks ids to names](https://github.com/zladx/LADX-Disassembly/blob/master/src/constants/sfx.asm#L5) – but it seems to be invalid: many names are not the correct ones. (See [src/constants/sfx.asm](https://github.com/zladx/LADX-Disassembly/blob/master/src/constants/sfx.asm#L5))

By listening to each music track, the constants could be renamed to have the correct names.

## How

Listening to a specific music track id in-game is easy:

1. Run the game in an emulator with a debugger (like BGB);
2. Go to the overworld;
3. Edit the memory at `$FFB0` (`hMusicTrack`), and write a track ID;
4. The music track should start playing.

**Comment by Drenn1** [comment]
I get the impression that - somehow - you were testing based on the values that D369 becomes. I think that D369 is the index for a specific bank (music_1.asm or music_2.asm). That is, each bank has its own internal index for the music tracks which gets converted. This is supported by the fact that you have exactly 0x40 entries, while there should be 0x70; but music_2.asm has 0x40 entries.

However, the tracks you've identified appear to come from both banks, so... I don't know what could have happened. I guess you must have been using a different variable for testing, or something.

Not sure if this is related, but writing to hMusicTrack seems to do nothing, I think you want wActiveMusicTrack (d368) instead for testing this.

**Comment by Vextrove** [comment]
https://github.com/Vextrove/LADX-Disassembly/blob/master/sfx.asm

I labelled the music files. I will not do jingles as I don't recognize them. 
The list has a lot of MUSIC_SILENCEs and MUSIC_GLITCHYs and a couple other track names connected to their IDs.

I've seen in the behaviour scripts that sounds and music are referenced using a label, like 
ld   a, WAVE_SFX_CUCOO_HURT
I assume some of the code still has a few ld commands that directly reference the music IDs rather than the labels? Can they even be made to reference a label rather than an ID without changing the hash?
