### ISSUE TITLE
Map disassembly inforation

### ISSUE THREAD

**Issue by Xkeeper0** [zladx/LADX-Disassembly#65]
Some notes while I'm here, since I got pinged and figured I'd drop by.

* The 'unreferenced' rooms in the overworld are all the "alternate" layouts for the given rooms. I'm not sure where or how these are swapped in, but they all come directly after the room they're an alternate of. For example, after the Egg, the unreferenced room is the Egg opened; for Eagle's Tower, the next one is the spun-around version, etc.
* The parser, as written, doesn't seem to have any understanding of object sizes. These are fairly simple to implement, at least. See the [Neo parser](https://github.com/Xkeeper0/links-awakening-junk/blob/master/neo/lib/LinksAwakening/RoomData.php#L51) for how they work. Short version:
  * Read high nybble of first byte of object data
  * `E`: Advance 5 bytes (warp data)
  * `C`: Advance 3 bytes (vertical object)
  * `8`: Advance 3 bytes (horizontal object)
  * `D`, `B`, `A`, `9`: ¯\\_(ツ)\_/¯ These don't seem to ever be used by the game.
  * `F`, `0-7`: Advance 2 bytes (standard object)
* The lack of the above means that `map_parser.py` currently treats any `FE` as an end-of-room marker, but this appears in warp data for a few rooms (namely `Overworld13` and `OverworldE3`, maybe others)
* `DungeonsAUnreferenced00` and `DungeonsAUnreferenced01` seem to be leftover end-of-room bytes! Kinda weird that they come right after two of the Instrument rooms...
* `DungeonsAUnreferenced02` is the alternate Goriya room you see when you have the Magnifying Glass.
* `DungeonsAUnreferenced03` and beyond are the Color Dungeon pointers (and rooms). You might need to add a manual exception for this in your parser.

Beyond that, nice work! I see it also handled the bizarre ordering of `Overworld63` well.

**Comment by kemenaran** [comment]
@Xkeeper0 Thanks for the notes! I'm really happy to have some feedback on this from more knowledgeable people.

I dispatched your comments to various issues, so I know what to do to improve the map parser.

Also, based on your comments, I started to create a wiki page to compile an exhaustive documentation on the [maps data format](https://github.com/mojobojo/LADX-Disassembly/wiki/Maps-data-format).

Same, this is pretty much a work in progress. But I hope it can be a good source of reference (rather than collecting bits of knowledge here and there).

(And I'll see if I can give editing rights on the Wiki to more people.)

**Comment by kemenaran** [comment]
@Xkeeper0 I mostly managed to implement your suggestions ; the maps and rooms disassembly is in a much better state now.

There is still room for improvement (track events, chest data, warp data, etc), but I'll close this issue for now. Thanks!
